### ISSUE TITLE
Når blir klienten publisert som en stabil versjon på Nuget?

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-net-klient#60]
Jeg ser at .Net klienten kun er tilgjengelig som prerelease.
Jeg lurer på når det kommer en stabil versjon publisert på NuGet?

**Comment by asjafjell** [comment]
Om du endrer fra _Include Prerelase_ til _Stable only_  i .Nuget packet manager så får du siste release som er stabil.

**Comment by aberner** [comment]
takk. Ser at det er en stund siden siste stabile.
Da må jeg omformulere spørsmålet og spørre om du har en dato for når neste stabile versjon vil komme.
jeg er på jakt etter funksjonaliteten for å sende til fysisk print.

har du en tentativ plan?

**Comment by asjafjell** [comment]
Fysisk print er ikke helt ferdigstilt - vi må kunne behandle kvittering for fysisk print fra Meldingsformidleren. Dette vil komme snarlig.

**Comment by asjafjell** [comment]
Fysisk print er ferdigstilt.
