### ISSUE TITLE
Oppgradert til ny versjon av .Net biblioteket - får feil i forbindelse med Avsenderidentifikator

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-net-klient#70]
har fått inn en feil fra en av de som utvikler integrasjon mot SDP.

De opplever en feil i forbindelse med integrasjonen mot SDP. Dette skjedde i forbindelse med at referansene til Sikker Digital Post .Net klienten ble vi oppgradert. En av tingene som var endret i forhold til den gamle referansen var bruken av avsenderidentifikator i forsendelsen, i tillegg til org.nr. Men siden avsenderidentifikator ikke er obligatorisk er ikke denne tatt i bruk.

men nå opplever man å få følgende feilmelding tilbake i kvittering:
```
 Avsender i manifest (no.difi.begrep.sdp.schema_v10.SDPAvsender@780d5ea4[organisasjon=no.difi.begrep.sdp.schema_v10.SDPOrganisasjon@64dc80d9[value=9908:<org.nr>, authority=ISO_6523_ACTORID_UPIS], avsenderidentifikator=<null>, fakturaReferanse=]) stemmer ikke overens med avsender i SDP (no.difi.begrep.sdp.schema_v10.SDPAvsender@7e313fdc[organisasjon=no.difi.begrep.sdp.schema_v10.SDPOrganisasjon@49958967[value=9908:<org.nr>, authority=ISO_6523_ACTORID_UPIS], avsenderidentifikator=, fakturaReferanse=])
```

ser at manifest.xml fila har: 
```
 avsenderidentifikator=<null> mens: sbd.digitalpost har avsenderidentifikator=
```

Er det noe avsender gjør feil, eller er dette en feil i klientbiblioteket?

**Comment by pereilif** [comment]
Hei,
Det er jeg som der den nevnte utvikleren. 

Etter tilbakemelding fra Arne om at Avsenderidentifikator-feltet i manifest.xml stod som NULL da det egentlig burde vært tomt la jeg inn kode som satt inn en tom streng i Avsenderidentifikator (Forsendelse.Behandlingsansvarlig.Avsenderidentifikator).
Etter det fungerte ekspederingen helt fint igjen.

Men det kunne kanskje vært en idé å ha tom verdi som default slik at ekspedering går igjennom dersom man ikke angir noe som helst på Avsenderidentifikator?

**Comment by asjafjell** [comment]
Hei, @pereilif!

Her har du helt rett. Avsenderidentifikator er et felt man kan sette om ønskelig ved oppretting av avsender. Hvis man bare har én avsender er det for mange naturlig å ikke sette det. Dette skal fikses så snart det lar seg gjøre. Fram til da kan du bare sette det til tom streng. 

Du hører fra meg så snart det er løst.

**Comment by asjafjell** [comment]
Løst i [release v1.2.5578.26671](https://github.com/difi/sikker-digital-post-net-klient/releases/tag/v1.2.5578.26671)
