### ISSUE TITLE
MD5 for sikker-digital-post.pfx

### ISSUE THREAD

**Issue by Landstad** [difi/sikker-digital-post-net-klient#72]
Jeg klonet denne i dag og skal forsøke å kjøre testklienten.

Fikk først feil om at filen "sikker-digital-post.pfx" ikke eksisterte i de ulike prosjektene. Slettet referansene siden filen ikke så ut til å være brukt.

Får da følgende feil istedenfor:
Unable to get MD5 checksum for the key file "..\sikker-digital-post.pfx". Could not find file '<fillokasjon>'.	SikkerDigitalPost.Domene.

Denne filen følger ikke med prosjektet og jeg tror ikke jeg har mottatt den, men det ser ut som den brukes til å signere solutionen eller noe?

Hva kan jeg gjøre for å komme rundt dette?

**Comment by asjafjell** [comment]
Hei, @Landstad 

Demoklienten blir ikke utviklet videre, da den blir alt for raskt utdatert. Mulighetene i SDP kan vanskelig beskrives med eksempelkode. For informasjon og oppsett se http://difi.github.io/sikker-digital-post-net-klient/
