### ISSUE TITLE
NuGet package: sikker-digital-post-NET-klient 

### ISSUE THREAD

**Issue by Landstad** [difi/sikker-digital-post-net-klient#73]
Vil bare nevne at det er en liten typo i introen http://difi.github.io/sikker-digital-post-net-klient/.

Dersom en søker på "sikker-digital-post-klient" finner en ingen ting. Jeg gjetter det skulle stått "sikker-digital-post-net-klient".

**Comment by asjafjell** [comment]
Takk for input. Det setter vi veldig pris på. Dette er fikset nå.
